dict1 = {
    "đi"                    :   "di",
    "đến"                   :   "den",
    "đi đến"                :   "di den",
    "đà nẵng"               :   "danang",
    "hồ chí minh"           :   "hochiminh",
    "hà nội"                :   "hanoi",
    "huế"                   :   "hue",
    "lúc"                   :   "WH_time",
    "vào lúc"               :   "WH_time",
    "lúc mấy giờ"           :   "WH_time",
    "vào lúc nào"           :   "WH_time",
    "xe"                    :   "xe",
    "xe buýt"               :   "xebuyt",
    "xe bus"                :   "xebus",
    "xe khách"              :   "xekhach",
    "xe đò"                 :   "xedo",
    "nào"                   :   "WH",
    "thành phố"             :   "thanhpho",
    "thành phố hồ chí minh" :   "hcmc",
    "thành phố hà nội"      :   "hanoi",
    "thành phố huế"         :   "hue", 
    "thành phố đà nẵng"     :   "danang",
    "thời gian"             :   "WH_time",
    "thời gian nào"         :   "WH_time",
    "vào thời gian nào"     :   "WH_time",
    "thời điểm"             :   "thoidiem",
    "thời điểm nào"         :   "WH_time",
    "từ"                    :   "from",
    "vào thời điểm nào"     :   "WH_time",
}

