pos_tag_dict = {
    "đi"                    :   "V",
    "đến"                   :   "V",
    "đi đến"                :   "V",
    "đà nẵng"               :   "Name",
    "hồ chí minh"           :   "Name",
    "hà nội"                :   "Name",
    "huế"                   :   "Name",
    "lúc"                   :   "WH_time",
    "vào lúc"               :   "WH_time",
    "lúc mấy giờ"           :   "WH_time",
    "vào lúc nào"           :   "WH_time",
    "xe"                    :   "N",
    "xe buýt"               :   "N",
    "xe bus"                :   "N",
    "xe khách"              :   "N",
    "xe đò"                 :   "N",
    "thành phố"             :   "N",
    "thành phố hồ chí minh" :   "Name",
    "thành phố hà nội"      :   "Name",
    "thành phố huế"         :   "Name", 
    "thành phố đà nẵng"     :   "Name",
    "thời gian"             :   "N_time",
    "thời gian nào"         :   "WH_time",
    "vào thời gian nào"     :   "WH_time",
    "thời điểm"             :   "N_time",
    "thời điểm nào"         :   "WH_time",
    "vào thời điểm nào"     :   "WH_time",
    'b1'                    :   "Name",
    'b2'                    :   "Name",
    'b3'                    :   "Name",
    'b4'                    :   "Name",
}